// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF3RxeGmSE6jjQhtS2w2Er2LkngKervaE',
    appId: '1:350841493755:web:6787ed58976e324f84785e',
    messagingSenderId: '350841493755',
    projectId: 'dresswind',
    authDomain: 'dresswind.firebaseapp.com',
    storageBucket: 'dresswind.appspot.com',
    measurementId: 'G-6HT0MPQLF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0I8kNmjPclV_ABePCQjSEpPjRPWtpfbY',
    appId: '1:350841493755:android:4c12455450d5a6be84785e',
    messagingSenderId: '350841493755',
    projectId: 'dresswind',
    storageBucket: 'dresswind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqcC-QpBc9JzSK4j6YnxUdqArOvF81zI',
    appId: '1:350841493755:ios:ff6359de975b682584785e',
    messagingSenderId: '350841493755',
    projectId: 'dresswind',
    storageBucket: 'dresswind.appspot.com',
    iosClientId: '350841493755-11kp293im0hojrjuu3rsrgkfjhr4ltqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dresswind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqcC-QpBc9JzSK4j6YnxUdqArOvF81zI',
    appId: '1:350841493755:ios:ff6359de975b682584785e',
    messagingSenderId: '350841493755',
    projectId: 'dresswind',
    storageBucket: 'dresswind.appspot.com',
    iosClientId: '350841493755-11kp293im0hojrjuu3rsrgkfjhr4ltqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dresswind',
  );
}
